#!/bin/bash
#
# c4 - Check CN Client Certificate
#
# You can run this from a CN like:
#
#   ./c4
#
# Or from your laptop like:
#
#   ./c4 cn-sandbox-unm-1.test.dataone.org
#
# Requires that you have sudo on the system.
# Assumes that the certificate is in /etc/dataone/client/private/urn*.pem

if [[ -z ${1} ]]; then
	RC='\033[0;31m'
	NC='\033[0m'
	TNOW=$(date -u +%s)
	expect_issuer="DataONE Production CA"
	host_name=$(hostname -f)
	environment="${host_name#*.}"
	if [[ "${environment}" == "test.dataone.org" ]]; then
		expect_issuer="DataONE Test Intermediate CA"
	fi
	_TMP=$(grep "cn.nodeId=" /etc/dataone/node.properties)
	node_id=${_TMP##*=}
	CERTIFICATES=($(find /etc/dataone/client/private -name "urn*.pem"))
	echo "Hostname  : ${host_name}"
	echo "cn.nodeId : ${node_id}"
	echo "Number of certificates : ${#CERTIFICATES[@]}"
	for CERTIFICATE in ${CERTIFICATES[@]}; do
	    echo "----"
		echo "  Filename: ${CERTIFICATE}"
		_TMP=$(openssl x509 -serial -noout -in ${CERTIFICATE})
		echo "  Serial  : ${_TMP##*=}"
		_TMP=$(openssl x509 -enddate -noout -in ${CERTIFICATE} \
		        | awk -F= ' /notAfter/ { printf("%s\n",$NF); } ');
		exp_date=$(date --date "${_TMP}" +%s)
		to_expire=$(echo "(${exp_date}-${TNOW})/(60*60*24)" |bc);
		if (("${to_expire}" < "30")); then
			echo -e "  Expires : ${RC}${_TMP}${NC}"
			echo -e "            ${RC}WARNING: Certificate expired or expiring!${NC}" 
		else	
			echo "  Expires : ${_TMP}"
		fi
		_TMP=$(openssl x509 -issuer -noout -in ${CERTIFICATE})
		issuer="${_TMP##*=}"
		if [[ ${issuer} != ${expect_issuer} ]]; then
			echo -e "  Issuer  : ${RC}${issuer}${NC}"
			echo -e "            ${RC}WARNING: Issuer expected to be: ${expect_issuer}${NC}"
		else
			echo -e "  Issuer  : ${issuer}"
		fi
		_TMP=$(openssl x509 -subject -noout -in ${CERTIFICATE})
		subject=${_TMP##*=}
		if [[ "${subject}" != "${node_id}" ]]; then
			echo -e "  Subject : ${RC}${subject}${NC}"
			echo -e "            ${RC}WARNING: subject != node.properties:cn.nodeId${NC}"
		else
			echo "  Subject : ${subject}"
		fi
	done
    echo "----"
else
	echo "Copying self to ${1}"
	scp -q ${0} ${1}:/tmp/c4
	echo "Executing sudo /tmp/c4"
	ssh -t ${1} 'chmod a+x /tmp/c4; sudo /tmp/c4; rm /tmp/c4'
fi

