#!/bin/bash

# Given name of a certificate, report on:
#  DN
#  Serial
#  Date created
#  Date of expiration
#  Days to expiration
#  Revocation status
#  Author
#
# Example:
# Show status of a single certificate in test environment:
#  
#   ./cert_status -A DataONETestIntCA/certs/urn\:node\:mnTestGulfWatch.pem  
#
#
# Example:
# Show status of a single certificate in production environment, using the 
# default locations for certificates and CRL:
#
#   ./cert_status -A -P DataONEProdCA/certs/urn\:node\:GULFWATCH.pem
# 
#    
# Example:
# Show status of a single certificate in production environment, explicitly
# indicating which certificates and CRL to use:
#
#   ./cert_status -A -r DataONEProdCA/crl/DataONEProdCA_CRL.pem \
#    -a DataONEProdCA/certs/DataONEProdCA.pem \
#    -c DataONERootCA/certs/DataONERootCA.pem \
#    DataONEProdCA/certs/urn\:node\:GULFWATCH.pem
#
#
# Example: 
# Generate a pipe delimited text file reporting on all 
# the test certificates:
#
#   ./cert_status -H > testcerts.csv; \
#   for f in $(find DataONETestIntCA/certs -name *.pem); \
#   do ./cert_status -A -s $f >> testcerts.csv; done
#  
# OR:
#
#   ./cert_status -s -A DataONETestIntCA/certs
#
# Example: 
# Generated a pipe delimited text file reporting on all
# the production certificates:
#
#   ./cert_status -H > testcerts.csv; \
#   for f in $(find DataONETestIntCA/certs -name *.pem); \
#   do ./cert_status -A -s \
#    -r DataONEProdCA/crl/DataONEProdCA_CRL.pem \
#    -a DataONEProdCA/certs/DataONEProdCA.pem \
#    -c DataONERootCA/certs/DataONERootCA.pem \
#   $f >> prodcerts.csv; done
#  
# OR:
#
#   ./cert_status -s -A -P DataONEProdCA/certs
#

VERSION="1.0.3"
INSTALLDIR=$(dirname ${0})
VERBOSE=""
CERTIFICATE=""
CAROOTCERT="${INSTALLDIR}/DataONETestCA/certs/DataONETestCA.pem"
CACERT="${INSTALLDIR}/DataONETestIntCA/certs/DataONETestIntCA.pem"
CRL="${INSTALLDIR}/DataONETestIntCA/crl/DataONETestInt_CRL.pem"
CACHAINFILE=""
cDN=""
cCreateDate=""
cExpireDate=""
cRevoked=""
cSerial=""
cAuthor=""
cValid=""
dumpCert=""
CSVOUTPUT=""
getAuthor=""
GENERATE_REPORT=""

XML=xml
SVN=svn
TMP="/tmp"
TMPFILE=${TMP}/$(basename $0).$$.out
dateformat_out="+%Y-%m-%dT%H:%M:%S.000+00:00"
TNOW=$(date -u +%s)

function usage() {
cat << EOF
$(basename $0) version ${VERSION}

usage: $(basename $0) OPTIONS Certificate 

Report on the status of a PEM format certificate.

OPTIONS:
  -h  Show this message
  -d  Text dump the certifcate to STDOUT and exit
  -v  Show version and exit
  -V  Verbose output to STDERR
  -s  Output pipe delimited rows instead of YAML
  -r  The CRL.pem file (${CRL})
  -a  The CACERT.pem file (${CACERT})
  -c  The CAROOTCERT.pem file (${CAROOTCERT})
  -C  CA Chain file, containing CACERT, CAROOT, and CRL
  -H  Generate CSV header and exit
  -A  Lookup author from subversion (default: No)
  -P  Use default production environment certs instead of test
  -R  Generate a report on all *.pem in the specified folder

EOF
}


function showVersion() {
	echo ${VERSION}
}


function log() {
	if [[ ! -z ${VERBOSE} ]]; then
		echo "LOG: $@" 1>&2;
	fi
}


function lwarn() {
	echo "WARN: $@" 1>&2;
}


function lerror() {
	echo "ERROR: $@" 1>&2;
}


function dumpCertificate() {
	openssl x509 -noout -text -in ${CERTIFICATE}
}


function toSerialDate() {
	if [[ $(uname) == "Darwin" ]]; then
		RES=$(date -junf "%b %e %H:%M:%S %Y %Z" "$@" +%s)
	else
		RES=$(date --date "${@}" +%s)
	fi
}


function fromSerialDate() {
	log "fromSerialDate"
	if [[ $(uname) == "Darwin" ]]; then
		RES=$(date -junf "%s" $@ ${dateformat_out})
	else
		RES=$(date --date @$@ ${dateformat_out})
	fi
}


function getCertificateInfo() {
	local _TMP=$(openssl x509 -subject -noout -in ${CERTIFICATE})
	old_IFS=$IFS
	IFS=$'/' _TMP=(${_TMP#*/})
	IFS=${old_IFS}
	_TMP=$(printf ",%s" "${_TMP[@]}")
	cDN=${_TMP:1}
	_TMP=$(openssl x509 -enddate -noout -in ${CERTIFICATE} \
		        | awk -F= ' /notAfter/ { printf("%s\n",$NF); } ');
	toSerialDate "${_TMP}"
	cExpireDate=${RES}
	_TMP=$(openssl x509 -startdate -noout -in ${CERTIFICATE} \
		        | awk -F= ' /notBefore/ { printf("%s\n",$NF); } ');		
	toSerialDate "${_TMP}"
	cCreateDate=${RES}
	_TMP=$(openssl x509 -serial -noout -in ${CERTIFICATE})
	cSerial=${_TMP##*=}
	cDaysToExpire=$(echo "(${cExpireDate}-${TNOW})/(60*60*24)" |bc);
	_TMP=""
	if [[ -z ${CACHAINFILE} ]]; then
	  	if [[ -f ${CAROOTCERT} ]]; then
			if [[ -f ${CACERT} ]]; then
				if [[ -f ${CRL} ]]; then
					cat ${CAROOTCERT} > ${TMPFILE}
					cat ${CACERT} >> ${TMPFILE}
					cat ${CRL} >> ${TMPFILE}
					CACHAINFILE=${TMPFILE}
				else
					log "CRL File not found: ${CRL}"
				fi
			else
				log "CACERT file not found: ${CACERT}"
			fi
		else
			log "CAROOTCERT file not found: ${CAROOTCERT}"
		fi
	fi
	if [[ -f ${CACHAINFILE} ]]; then
		cRevoked="Not_Revoked"
		cValid="Valid"
		log "CACHAINFILE = ${CACHAINFILE}"
		old_IFS=$IFS
		IFS=$'\n' _TMP=($(openssl verify -crl_check -CAfile ${CACHAINFILE} ${CERTIFICATE}))
		IFS=${old_IFS}
		for sslError in "${_TMP[@]}"; do
			if [[ $sslError == 'error'* ]]; then
				lwarn $sslError
				if [[ $sslError == 'error 23'* ]]; then
					cRevoked="Revoked"
				fi
				if [[ $sslError == 'error 20'* ]]; then
					cValid="Invalid"
				fi
			fi
		done
	else
		log "CACHAINFILE file not found: ${CACHAINFILE}"
	fi
	if [[ ! -z ${getAuthor} ]]; then
		cAuthor=$(${SVN} blame --xml ${CERTIFICATE} | ${XML} sel -t -m "//entry[1]/commit" -v "author" -n)
	fi
}


function showCertificateInfo() {
	fromSerialDate ${cCreateDate}
	local cdate=${RES}
	fromSerialDate ${cExpireDate}
	local edate=${RES}
	if [[ ${CSVOUTPUT} == "1" ]]; then
		echo "${CERTIFICATE}|${cSerial}|${cDN}|${cRevoked}|${cValid}|${cDaysToExpire}|${edate}|${cdate}|${cAuthor}"
	else
		echo "----"
		echo "File_name: \"${CERTIFICATE}\""
		echo "    Author      : ${cAuthor}"
		echo "    Serial      : ${cSerial}"
		echo "    DN          : \"${cDN}\""
		echo "    Created     : ${cdate}"
		echo "    Expires     : ${edate}"
		echo "    Expires_days: ${cDaysToExpire}"
		echo "    Revocation  : ${cRevoked}"
		echo "    Validity    : ${cValid}"
	fi
}


function showHeader() {
	if [[ -z ${CSVOUTPUT} ]]; then
		echo "#Certificate Status"
		echo "Generated: $(date ${dateformat_out})"
	else
		echo "#Certificate Status"
		echo "#Generated|$(date ${dateformat_out})"
		echo "#"
		echo "File|Serial|DN|Revoked|Validity|Expire_days|Expires|Created|Author"
	fi
}


#=== Main ===
while getopts "hvVdsHAPr:a:c:C:" OPTION
do
	case ${OPTION} in
		h) usage; exit 1;;
		v) showVersion; exit 1;;
		d) dumpCert=1;;
		V) VERBOSE=1;;
		r) CRL=$OPTARG;;
		a) CACERT=$OPTARG;;
		c) CAROOTCERT=$OPTARG;;
		C) CACHAINFILE=$OPTARG;;
		s) CSVOUTPUT=1;;
		H) showHeader; exit 1;;
		A) getAuthor=1;;
		P) CAROOTCERT="${INSTALLDIR}/DataONERootCA/certs/DataONERootCA.pem";
		   CACERT="${INSTALLDIR}/DataONEProdCA/certs/DataONEProdCA.pem";
		   CRL="${INSTALLDIR}/DataONEProdCA/crl/DataONEProdCA_CRL.pem";;
		\?) usage; exit 1;;
	esac
done

shift $(($OPTIND - 1))
if [[ -z ${1} ]]; then
		lerror "Certificate file name or folder is required"
		exit 1
fi
TARGET=${1}
if [[ -f ${TARGET} ]]; then
	# Report on single certificate
	CERTIFICATE=${TARGET}
	log "Certificate file: ${CERTIFICATE}"
	if [[ ! -z ${dumpCert} ]]; then
		dumpCertificate
		exit;
	fi
	getCertificateInfo
	showCertificateInfo
else
	if [[ -d ${TARGET} ]]; then
		# Report on *.pem in folder
		showHeader
		CERTIFICATES=$(find ${TARGET} -name "*.pem")
		for CERTIFICATE in ${CERTIFICATES}; do
			log "Certificate file: ${CERTIFICATE}"
			getCertificateInfo
			showCertificateInfo
		done
	else
		lerror "Supplied target is not a file or folder"
		exit
	fi
fi
